if(EXISTS "/home/zzy/CMU15-445/build-release/test/catalog_test[1]_tests.cmake")
  include("/home/zzy/CMU15-445/build-release/test/catalog_test[1]_tests.cmake")
else()
  add_test(catalog_test_NOT_BUILT catalog_test_NOT_BUILT)
endif()
