if(EXISTS "/home/zzy/CMU15-445/build-release/test/clock_replacer_test[1]_tests.cmake")
  include("/home/zzy/CMU15-445/build-release/test/clock_replacer_test[1]_tests.cmake")
else()
  add_test(clock_replacer_test_NOT_BUILT clock_replacer_test_NOT_BUILT)
endif()
