if(EXISTS "/home/zzy/CMU15-445/build-release/test/deadlock_detection_test[1]_tests.cmake")
  include("/home/zzy/CMU15-445/build-release/test/deadlock_detection_test[1]_tests.cmake")
else()
  add_test(deadlock_detection_test_NOT_BUILT deadlock_detection_test_NOT_BUILT)
endif()
