if(EXISTS "/home/zzy/CMU15-445/build-release/test/disk_manager_test[1]_tests.cmake")
  include("/home/zzy/CMU15-445/build-release/test/disk_manager_test[1]_tests.cmake")
else()
  add_test(disk_manager_test_NOT_BUILT disk_manager_test_NOT_BUILT)
endif()
