if(EXISTS "/home/zzy/CMU15-445/build-release/test/grading_buffer_pool_manager_instance_test[1]_tests.cmake")
  include("/home/zzy/CMU15-445/build-release/test/grading_buffer_pool_manager_instance_test[1]_tests.cmake")
else()
  add_test(grading_buffer_pool_manager_instance_test_NOT_BUILT grading_buffer_pool_manager_instance_test_NOT_BUILT)
endif()
