if(EXISTS "/home/zzy/CMU15-445/build-release/test/recovery_test[1]_tests.cmake")
  include("/home/zzy/CMU15-445/build-release/test/recovery_test[1]_tests.cmake")
else()
  add_test(recovery_test_NOT_BUILT recovery_test_NOT_BUILT)
endif()
