if(EXISTS "/home/zzy/CMU15-445/build-release/test/rwlatch_test[1]_tests.cmake")
  include("/home/zzy/CMU15-445/build-release/test/rwlatch_test[1]_tests.cmake")
else()
  add_test(rwlatch_test_NOT_BUILT rwlatch_test_NOT_BUILT)
endif()
