if(EXISTS "/home/zzy/CMU15-445/build-release/test/type_test[1]_tests.cmake")
  include("/home/zzy/CMU15-445/build-release/test/type_test[1]_tests.cmake")
else()
  add_test(type_test_NOT_BUILT type_test_NOT_BUILT)
endif()
